export const FutsalCourts = [
  {
    value: "Grassroots Recreational Center",
    label: "Grassroots Recreational Center",
    location: "Mandikatar, Kathmandu",
    contact: "4375276",
    numberOfFields: 2,
    additionalInfo: "Swimming Pool, Big Parking, Free Wi-Fi, Cafe",
  },
  {
    value: "Maidan Futsal",
    label: "Maidan Futsal",
    location: "Battisputali, Kathmandu",
    contact: "01-4497642, 9721589931",
    numberOfFields: 1,
    additionalInfo: "Free Wi-Fi, Cafe",
  },
  {
    value: "X-Cel Recreation Centre",
    label: "X-Cel Recreation Centre",
    location: "Baluwatar, Kathmandu",
    contact: "01-4440857, 9841595814",
    numberOfFields: 2,
    additionalInfo:
      "Opening Soon - Swimming Pool (Adult and Children) & Steam/Sauna",
  },
  {
    value: "Futsal Arena (Thamel)",
    label: "Futsal Arena (Thamel)",
    location: "GAA Hall, Thamel, Kathmandu",
    contact: "4433515",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Futsal Arena (Bouddha)",
    label: "Futsal Arena (Bouddha)",
    location: "Bouddha, Kathmandu",
    contact: "9801070700",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Royal Futsal",
    label: "Royal Futsal",
    location: "Thapagaun, Anamnagar, Kathmandu",
    contact: "980-8192257",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Kathmandu Futsal",
    label: "Kathmandu Futsal",
    location: "Lalitpur",
    contact: "9851137525, 9802021223, 9803024359",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Prismatic Futsal & Recreation Center",
    label: "Prismatic Futsal & Recreation Center",
    location: "Sanepa, Lalitpur",
    contact: "01-5521587",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Dhuku Futsal Hub",
    label: "Dhuku Futsal Hub",
    location: "Sital Marg, Maharajgunj, Kathmandu",
    contact: "4435832",
    numberOfFields: 2,
    additionalInfo: "",
  },
  {
    value: "BG Brothers Health Club PVT. LTD.",
    label: "BG Brothers Health Club PVT. LTD.",
    location: "Pepsicola, Kathmandu",
    contact: "01-4992433, 980-3604020",
    numberOfFields: 2,
    additionalInfo: "",
  },
  {
    value: "White Horse Futsal Center",
    label: "White Horse Futsal Center",
    location: "Sukedhara Nilopool, Kathmandu",
    contact: "014015067, 9849961991",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "ARM Futsal Station",
    label: "ARM Futsal Station",
    location: "Sanepa, Lalitpur",
    contact: "01-5541495",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Rave Futsal Center",
    label: "Rave Futsal Center",
    location: "Ekatabasti, Sukedhara, Kathmandu",
    contact: "014374343, 9841223162",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Goalz!! Futsal@Mela",
    label: "Goalz!! Futsal@Mela",
    location: "Bhrikutimandap, Kathmandu",
    contact: "0980-3641222",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Shantinagar Futsal",
    label: "Shantinagar Futsal",
    location: "Shanti Chowk, Shantinagar-32, Kathmandu",
    contact: "985-1188182, 01-4108159",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Kirtipur Futsal",
    label: "Kirtipur Futsal",
    location: "Nagaun, Kirtipur",
    contact: "9818149835",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Shankhamul Futsal",
    label: "Shankhamul Futsal",
    location: "Shankhamul, Baneshwor, Kathmandu",
    contact: "01-4782088, 9841567114",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Buddhanagar Futsal",
    label: "Buddhanagar Futsal",
    location: "Buddhanagar, Baneshwor, Kathmandu",
    contact: "01-4782002",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Samakhushi Futsal",
    label: "Samakhushi Futsal",
    location: "Samakhusi, Kathmandu",
    contact: "01-4363834",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Badminton Hall G4 Futsal",
    label: "Badminton Hall G4 Futsal",
    location: "Tarkeshwor, Manamaiju, Kathmandu",
    contact: "980-3259660",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Manang Marshyangdi Futsal",
    label: "Manang Marshyangdi Futsal",
    location: "Samakhusi, Kathmandu",
    contact: "01-6200126",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Bhaktapur Futsal",
    label: "Bhaktapur Futsal",
    location: "Araniko Highway, Sallaghari, Bhaktapur",
    contact: "984-0252869, 01-6610404",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Shooters Futsal",
    label: "Shooters Futsal",
    location: "Araniko Highway, Sallaghari, Bhaktapur",
    contact: "01-6610404, 9841610404",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Banepa Futsal",
    label: "Banepa Futsal",
    location: "Banepa, Kavrepalanchok",
    contact: "9851030986",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Chitwan Futsal",
    label: "Chitwan Futsal",
    location: "Bharatpur, Chitwan",
    contact: "9845058217",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Hetauda Futsal",
    label: "Hetauda Futsal",
    location: "Hetauda, Makwanpur",
    contact: "9802080415",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Butwal Futsal",
    label: "Butwal Futsal",
    location: "Butwal, Rupandehi",
    contact: "9847025526",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Pokhara Futsal",
    label: "Pokhara Futsal",
    location: "Pokhara, Kaski",
    contact: "9802825589",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Dharan Futsal",
    label: "Dharan Futsal",
    location: "Dharan, Sunsari",
    contact: "9817357420",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Biratnagar Futsal",
    label: "Biratnagar Futsal",
    location: "Biratnagar, Morang",
    contact: "9852023456",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Birtamod Futsal",
    label: "Birtamod Futsal",
    location: "Birtamod, Jhapa",
    contact: "9804365874",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Dhangadhi Futsal",
    label: "Dhangadhi Futsal",
    location: "Dhangadhi, Kailali",
    contact: "9848454123",
    numberOfFields: 1,
    additionalInfo: "",
  },
  {
    value: "Nepalgunj Futsal",
    label: "Nepalgunj Futsal",
    location: "Nepalgunj, Banke",
    contact: "9802154863",
    numberOfFields: 1,
    additionalInfo: "",
  },
];
