export const myBooking = [
    {
      id: "584126",
      venue: "Play Zone",
      location: "Diabari, Uttara Dhaka",
      status: "upcoming",
      paymentStatus: "Fully Paid",
      date: "July 2023, Saturday",
      time: "10:00 AM-11:00 AM",
      price: 3500,
    },
    {
      id: "584125",
      venue: "Play Zone",
      location: "Diabari, Uttara Dhaka",
      status: "upcoming",
      paymentStatus: "Partially Paid",
      date: "July 2023, Saturday",
      time: "10:00 AM-11:00 AM",
      price: 3500,
    },
    {
      id: "584124",
      venue: "Play Zone",
      location: "Diabari, Uttara Dhaka",
      status: "canceled",
      paymentStatus: "Refunded",
      date: "July 2023, Saturday",
      time: "10:00 AM-11:00 AM",
      price: 3500,
    },
    {
      id: "584123",
      venue: "Play Zone",
      location: "Diabari, Uttara Dhaka",
      status: "past",
      paymentStatus: "Pending refund",
      date: "July 2023, Saturday",
      time: "10:00 AM-11:00 AM",
      price: 3500,
    },
    {
      id: "584122",
      venue: "Play Zone",
      location: "Diabari, Uttara Dhaka",
      status: "past",
      paymentStatus: "Fully Paid",
      date: "July 2023, Saturday",
      time: "10:00 AM-11:00 AM",
      price: 3500,
    },
  ];